SELECT RIGHT(REPLICATE('0',9)+'22',2);
SELECT ISNULL(MAX(FORM_NO),0)+1 FROM FORMS
select RIGHT(REPLICATE('0',4)+CAST(YEAR(GETDATE()) AS VARCHAR),4);
select RIGHT(REPLICATE('0',2)+CAST(MONTH(GETDATE()) AS VARCHAR),2);
select RIGHT(REPLICATE('0',2)+CAST(DAY(GETDATE()) AS VARCHAR),2);
select RIGHT(REPLICATE('0',5)+CAST(2 AS VARCHAR),4);

select REPLICATE('0',2)